package com.jara.drools.example;

import com.jara.drools.example.model.Person;
import com.jara.drools.example.model.Pet;
import com.jara.drools.example.model.Firefighter;
import com.jara.drools.example.model.Pet.PetType;
import com.jara.example.tipos.*

// The rules for the cat in the tree example

rule "Call the fire department"
    when
        $p: Person($pet: pet, petCallCount > 0)
        $cat: Pet(this == $pet, position == "on a limb", type == PetType.CAT)
    then
    	    	
       System.out.println($p.getName()+": Hello... Fire Department? My Cat is on a tree. Please help me.");
       Firefighter firefighter = new Firefighter("Fred");
       insert(firefighter);
end

rule "Firefighter gets the cat down"
    when
    	$f: Firefighter()
        $p: Person($pet: pet, petCallCount > 0)
        $cat: Pet(this == $pet, position == "on a limb", type == PetType.CAT)
    then
       System.out.println("Firefighter " +$f.getName()+": I'm getting the cat down.");
       $cat.setPosition("on the street");
       retract($f);
       update($cat);
end

rule "Call a Cat when it is in a tree"
    when
        $p: Person($pet: pet, petCallCount == 0) 
        $cat: Pet(this == $pet, position == "on a limb", type == PetType.CAT)
    then
       System.out.println($p.getName()+": "+$cat.getName() + " come down!");
       $p.setPetCallCount($p.getPetCallCount()+1);
       update($p);
end

rule "Your First Rule"
    when
        not(Tipo1() )
    then
        System.out.println("Hola, no existe un Tipo1 desde FirefighterCatKBase");
end